---
title: "motivating example"
author: "Donny Williams"
date: "8/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Required packages
```{r}
library(BGGM)
library(ggplot2)
library(corpcor)
library(GGMnonreg)
library(MASS)
library(ggthemes)
library(cowplot)
```

Note that the first three can be installed from CRAN with `install.packages()`, whereas the third can be installed
from github with `devtools::install_github("donaldRwilliams/GGMnonreg")`. 

## Figure 1: Sample Correlations

```{r}
# correlations
cors <- BGGM::ptsd_cor1

pcs <- corpcor::cor2pcor(cors)

data1 <- pcs[upper.tri(pcs)]

data2 <- cors[upper.tri(cors)]




dat <- data.frame(x = c(data1, data2), 
               Type=rep(c("Partial", "Zero-order"), 
                        c(length(data1), length(data2))))
ggplot(dat) + 
  geom_histogram(aes(x = x, 
                     fill = Type), 
                 colour ="black", 
                 alpha = 0.60, 
                 position="identity", 
                 binwidth = .025, 
                 size = 0.5) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(), 
        legend.position = "top", 
        axis.title = element_text(size = 14), 
        legend.text = element_text(size = 12), 
        panel.grid.major = element_line(color = "grey90", 
                                        linetype = "dotted"), legend.title = element_blank()) +
  scale_y_continuous(expand = c(0,0), 
                     limits = c(0, 16), 
                     breaks = seq(0,15,5)) +
  ylab("Count") +
  xlab("Sample Correlation Coefficients") +
  scale_fill_manual(values = c("#CC79A7", "#009E73"), 
                    labels = c(expression("Partial"~"("*italic(p)~"= 16)")," Zero-Order"))

```


## Figure 2A: Controlling for Variables

```{r}
n <- seq(150, 500)
ord <- c(0, seq(20, 100, 20))
reps <- c(2, 4, 8)

ls <- list()

for(i in 1:length(ord)){
  ls[[i]] <-  do.call(rbind.data.frame, lapply(1:3, function(x) { 
    temp <- power_z(r = 0.2, 
                    c = ord[i], 
                    n = n)^reps[x]
    data.frame(order = ord[i], 
               n = n, 
               power = temp, group = paste("Networks =", reps[x]))
  }))
}


dat <- do.call(rbind.data.frame, 
               ls)

dat$facet <- "one"

dat$facet <- factor(dat$facet, levels = c("one"),
                   labels = expression(italic(rho)~"= 0.10"))

plot_2a <- ggplot(dat, aes(x = as.factor(n), 
                     y = power, 
                     color = as.factor(order), 
                     group = as.factor(order))) +
  theme_bw() +
  facet_grid(~ group) +
  annotate("rect", xmin = -Inf, 
           xmax = Inf, ymin = 0.80, 
           ymax = Inf, alpha = 0.1) +
  geom_hline(yintercept = 0.80, 
             linetype = "dotted") +
  geom_line(size = 1.5, alpha = .8) +
  scale_y_continuous(breaks = seq(0, 1, 0.2)) +
  theme(panel.grid = element_blank(),   
         axis.title = element_text(size = 14), 
         legend.text = element_text(size = 12), 
        legend.position = "top",
        strip.background = element_rect(fill = "grey97"),
        axis.text.x = element_text(angle = 90, vjust = 0),
        panel.spacing = unit(2, "lines"), 
        plot.title = element_text(size = 20)
        ) +
  ggthemes::scale_color_colorblind(name = "Order") +
  guides(color = guide_legend(override.aes = list(alpha = 1))) +
  scale_x_discrete( breaks = seq(150, 500, 1), 
                    labels = c("150", rep("", 349), "500")) +
  ylab("Probability") +
  xlab("Sample Size") +
  guides(col = guide_legend(nrow = 1, 
                            byrow = TRUE, 
                            override.aes = list(alpha = 1))) 
  

plot_2a
```


# Figure 2B: Simulation
```{r}
n <- 800
sims <- 5000
true <- diag(4)
true[upper.tri(true)] <- 0.10
true[lower.tri(true)] <- 0.10
cors <- corpcor::pcor2cor(true)


pcor2_ls <- list()
pcor3_ls <- list()
pcor4_ls <- list()


cor2_ls <- list()
cor3_ls <- list()
cor4_ls <- list()
for(i in 1:sims){
print(i)
Y1 <- MASS::mvrnorm(n = n, mu = rep(0, 4), Sigma = cors)
Y2 <- MASS::mvrnorm(n = n, mu = rep(0, 4), Sigma = cors)
Y3 <- MASS::mvrnorm(n = n, mu = rep(0, 4), Sigma = cors)
Y4 <- MASS::mvrnorm(n = n, mu = rep(0, 4), Sigma = cors)


cor_pvalues1 <- ifelse( cor_test(cor(Y1), n = n, c = 0)[upper.tri(diag(4))] < 0.05, 1, 0)
cor_pvalues2 <- ifelse( cor_test(cor(Y2), n = n, c = 0)[upper.tri(diag(4))] < 0.05, 1, 0)
cor_pvalues3 <- ifelse( cor_test(cor(Y3), n = n, c = 0)[upper.tri(diag(4))] < 0.05, 1, 0)
cor_pvalues4 <- ifelse( cor_test(cor(Y4), n = n, c = 0)[upper.tri(diag(4))] < 0.05, 1, 0)



res_cor2 <- as.data.frame( t(rbind(cor_pvalues1, cor_pvalues2)))
res_cor2$tally  <- rowSums(res_cor2)

res_cor3 <- as.data.frame(t(rbind(cor_pvalues1, cor_pvalues2, cor_pvalues3)))
res_cor3$tally  <- rowSums(res_cor3)

res_cor4 <- as.data.frame(t(rbind(cor_pvalues1, cor_pvalues2, cor_pvalues3, cor_pvalues4)))
res_cor4$tally  <- rowSums(res_cor4)


cor2_ls[[i]] <- data.frame(nets = 2,
                           replicated = sum(res_cor2$tally == 2),
                           type = "cor")

cor3_ls[[i]] <- data.frame(nets = 3,
                           replicated = sum(res_cor3$tally == 3),
                           type = "cor")
cor4_ls[[i]] <- data.frame(nets = 4, replicated = sum(res_cor4$tally == 4), 
                           type = "cor")


pcor_pvalues1 <- ifelse(cor_test(corpcor::cor2pcor(cor(Y1)), n = n, c = 2)[upper.tri(diag(4))] < 0.05, 1, 0)
pcor_pvalues2 <- ifelse(cor_test(corpcor::cor2pcor(cor(Y2)), n = n, c = 2)[upper.tri(diag(4))] < 0.05, 1, 0)
pcor_pvalues3 <- ifelse(cor_test(corpcor::cor2pcor(cor(Y3)), n = n, c = 2)[upper.tri(diag(4))] < 0.05, 1, 0)
pcor_pvalues4 <- ifelse(cor_test( corpcor::cor2pcor(cor(Y4)), n = n, c = 2)[upper.tri(diag(4))] < 0.05, 1, 0)

res_pcor2 <- as.data.frame( t(rbind(pcor_pvalues1, pcor_pvalues2)))
res_pcor2$tally  <- rowSums(res_pcor2)

res_pcor3 <- as.data.frame(t(rbind(pcor_pvalues1, pcor_pvalues2, pcor_pvalues3)))
res_pcor3$tally  <- rowSums(res_pcor3)

res_pcor4 <- as.data.frame(t(rbind(pcor_pvalues1, pcor_pvalues2, pcor_pvalues3, pcor_pvalues4)))
res_pcor4$tally  <- rowSums(res_pcor4)


pcor2_ls[[i]] <- data.frame(nets = 2, replicated = sum(res_pcor2$tally == 2), type = "pcor")
pcor3_ls[[i]] <- data.frame(nets = 3, replicated = sum(res_pcor3$tally == 3), type = "pcor")
pcor4_ls[[i]] <- data.frame(nets = 4, replicated = sum(res_pcor4$tally == 4), type = "pcor")

}

res_cor <- rbind.data.frame( 
data.frame(type = "cor", net = 2, edges = 0:6,
prob =  sapply(0:6, function(x) mean( do.call(rbind.data.frame, cor2_ls)[,2] == x))
),
data.frame(type = "cor", net = 3,edges = 0:6,
           prob =  sapply(0:6, function(x) mean( do.call(rbind.data.frame, cor3_ls)[,2] == x))
),
data.frame(type = "cor", net = 4, edges = 0:6,
           prob =  sapply(0:6, function(x) mean( do.call(rbind.data.frame, cor4_ls)[,2] == x))
))


res_pcor <- rbind.data.frame( 
  data.frame(type = "pcor", net = 2, edges = 0:6,
             prob =  sapply(0:6, function(x) mean( do.call(rbind.data.frame, pcor2_ls)[,2] == x))
  ),
  data.frame(type = "pcor", net = 3,edges = 0:6,
             prob =  sapply(0:6, function(x) mean( do.call(rbind.data.frame, pcor3_ls)[,2] == x))
  ),
  data.frame(type = "pcor", net = 4, edges = 0:6,
             prob =  sapply(0:6, function(x) mean( do.call(rbind.data.frame, pcor4_ls)[,2] == x))
  ))

dat_plot <- rbind.data.frame(
  res_cor,
  res_pcor
)

dat_plot$groups <- factor(dat_plot$net, 
                          levels = c(2, 3, 4),
                          labels = c("Networks = 2", 
                                     "Networks =  3", 
                                     "Networks = 4"))



dat_plot$type <- factor(dat_plot$type, 
                        levels= c("pcor", "cor"),
                        labels = c("GGM", "Association"))

plot_2b <- ggplot(dat_plot, aes(x = factor(edges), 
                                y = prob, 
                                fill = type)) +
  theme_bw() +
   theme(panel.grid = element_blank(),   
         axis.title = element_text(size = 14), 
         legend.text = element_text(size = 12), 
        legend.position = "top",
        strip.background = element_rect(fill = "grey97"),
        plot.title = element_text(size = 20),
         panel.spacing = unit(2, "lines")
        ) +
  geom_col(position = "dodge", 
           width = 0.75, 
           color = "black") +
  labs(x = "Successfully Replicated Edges",
       y = "Probability") +
  scale_y_continuous(limits = c(0, 1), 
                     breaks = seq(0, 1, 0.2), 
                     expand = c(0, 0)) +
  facet_grid(~ groups) +
  scale_fill_manual(name ="", 
                    values = c("#CC79A7", 
                               "#999999")) +
  scale_x_discrete(labels = c(expression(frac("0","6")),  
                              expression(frac("1","6")),
                              expression(frac("2","6")),
                              expression(frac("3","6")),
                              expression(frac("4","6")),
                              expression(frac("5","6")),
                              expression(frac("6","6"))
                              ))

plot_2b
```


# Figure 2: Combine
```{r}
cowplot::plot_grid(plot_2a, 
          "",
          plot_2b, 
          nrow = 3,
          rel_heights = c(1, 0.1, 1.075),
          labels = c("A", "", "B"), 
          label_size = 22,
          label_fontface = "plain")
```






# Figure 4: BFI
```{r}
pcors_bfi <- corpcor::cor2pcor( cor(na.omit(BGGM::bfi[,1:25])))

# bfi
n <- c(500, 1000, 2000)
alpha <- c(0.05)

net_bfi <- ifelse(abs(pcors_bfi[upper.tri(pcors_bfi)]) < 0.05, 0,  
         pcors_bfi[upper.tri(pcors_bfi)] )


edges_bfi <- abs(net_bfi[net_bfi != 0])

p <- ncol(pcors_bfi)
n_t <- 0.5 * (p * (p-1))
n_e <- length(edges_bfi)


res_bfi <- lapply(1:length(n), function(x){
  
  pwr_un <- power_z(edges_bfi, n = n[x], c = p - 2, alpha = 0.05)
  pwr_cor <- power_z(edges_bfi, n = n[x], c = p - 2, alpha = 0.05 / n_t)

  

dat_un <- data.frame(x = rep(0:n_e,2), 
           Networks = rep(c('2_un', "4_un"), each = n_e + 1),
           prob = c(poibin::dpoibin(0:n_e, 
                                    pp = pwr_un^2), 
                    poibin::dpoibin(0:n_e, 
                                    pp = pwr_un^4)),
           sample = paste0("N = ", n[x]), alpha = "un")

dat_cor <- data.frame(x = rep(0:n_e,2), 
                     Networks = rep(c('2_cor', "4_cor"), each = n_e + 1),
                     prob = c(poibin::dpoibin(0:n_e, 
                                              pp = pwr_cor^2), 
                              poibin::dpoibin(0:n_e, 
                                              pp = pwr_cor^4)),
                     sample = paste0("N = ", n[x]), alpha = "cor")

rbind.data.frame(dat_un, dat_cor)

})


dat_res <- do.call(rbind.data.frame, res_bfi)
dat_res$facet <- "BFI"

dat_res$n_new <- factor(dat_res$sample, 
                        levels = rev(unique(dat_res$sample)), 
                        labels = rev(unique(dat_res$sample)))

plt_bfi <- ggplot(data =  dat_res,
                  aes(
                    x = x,
                    y  = prob,
                    group = Networks,
                    fill = Networks
                  )) +
  geom_area(position  = "identity",
            alpha = 0.75,
            color = "black") +
  theme_bw() +
  geom_vline(xintercept = 0.50 * n_e,
             linetype = "dotted",
             size = 0.5) +
  annotate(
    "rect",
    ymin = 0,
    ymax = Inf,
    xmin = 0.50 * n_e,
    xmax = Inf ,
    alpha = 0.05
  ) +
  geom_vline(xintercept = 0.50 * n_e,
             linetype = "dotted",
             size = 0.5) +
  
  theme(
    legend.position = "top",
    panel.spacing.y =  unit(1, "lines"),
    panel.grid = element_blank(),
    axis.title = element_text(size = 12),
    strip.background = element_rect(fill = "grey97"),
    strip.background.y = element_blank(),
    strip.text.y = element_blank()
  )  +
  scale_fill_manual(values = c("#56B4E9", "#0072B2", "#E69F00",  "#D55E00")) +
  scale_x_continuous(
    limits = c(0, n_e),
    breaks = c(0,
               0.25 * n_e,
               0.50 * n_e,
               0.75 * n_e,
               1 * n_e),
    labels = c("0%",
               "25%",
               "50%",
               "75%", "100%")
  ) +
  xlab("") +
  ylab("Probability") +
  facet_grid(n_new ~ facet, scales = "free_y") +
  scale_y_continuous(expand = c(0, 0)) 
```


# Figure 4: PTSD

```{r}
pcors_ptsd <- corpcor::cor2pcor(cor(na.omit(BGGM::ptsd)))

net_ptsd <-
  ifelse(abs(pcors_ptsd[upper.tri(pcors_ptsd)]) < 0.05, 0,
         pcors_ptsd[upper.tri(pcors_ptsd)])


edges_ptsd <- abs(net_ptsd[net_ptsd != 0])

p <- ncol(pcors_ptsd)
n_t <- 0.5 * (p * (p - 1))
n_e <- length(edges_ptsd)


res_ptsd <- lapply(1:length(n), function(x) {
  pwr_un <- power_z(edges_ptsd,
                    n = n[x],
                    c = p - 2,
                    alpha = 0.05)
  pwr_cor <-
    power_z(edges_ptsd,
            n = n[x],
            c = p - 2,
            alpha = 0.05 / n_t)
  
  
  
  dat_un <- data.frame(
    x = rep(0:n_e, 2),
    Networks = rep(c('2_un', "4_un"), each = n_e + 1),
    prob = c(
      poibin::dpoibin(0:n_e,
                      pp = pwr_un ^ 2),
      poibin::dpoibin(0:n_e,
                      pp = pwr_un ^ 4)
    ),
    sample = paste0("N = ", n[x]),
    alpha = "un"
  )
  
  dat_cor <- data.frame(
    x = rep(0:n_e, 2),
    Networks = rep(c('2_cor', "4_cor"), each = n_e + 1),
    prob = c(
      poibin::dpoibin(0:n_e,
                      pp = pwr_cor ^ 2),
      poibin::dpoibin(0:n_e,
                      pp = pwr_cor ^ 4)
    ),
    sample = paste0("N = ", n[x]),
    alpha = "cor"
  )
  
  rbind.data.frame(dat_un, dat_cor)
  
})




dat_res <- do.call(rbind.data.frame, res_ptsd)
dat_res$facet <- "PTSD"


dat_res$n_new <- factor(dat_res$sample,
                        levels = rev(unique(dat_res$sample)),
                        labels = rev(unique(dat_res$sample)))

plt_ptsd <- ggplot(data =  dat_res,
                   aes(
                     x = x ,
                     y  = prob,
                     group = Networks,
                     fill = Networks
                   )) +
  geom_area(position  = "identity",
            alpha = 0.75,
            color = "black") +
  theme_bw() +
  geom_vline(xintercept = 0.50 * n_e,
             linetype = "dotted",
             size = 0.5) +
  annotate(
    "rect",
    ymin = 0,
    ymax = Inf,
    xmin = 0.50 * n_e,
    xmax = Inf ,
    alpha = 0.05
  ) +
  geom_vline(xintercept = 0.50 * n_e,
             linetype = "dotted",
             size = 0.5) +
  
  theme(
    legend.position = "top",
    panel.spacing.y =  unit(1, "lines"),
    panel.grid = element_blank(),
    axis.title = element_text(size = 12),
    strip.background = element_rect(fill = "grey97"),
    strip.background.y = element_blank(),
    strip.text.y = element_blank(),
  )  +
  scale_fill_manual(values = c("#56B4E9", "#0072B2", "#E69F00",  "#D55E00")) +
  scale_x_continuous(
    limits = c(0, n_e),
    breaks = c(0,
               0.25 * n_e,
               0.50 * n_e,
               0.75 * n_e,
               1 * n_e),
    labels = c("0%",
               "25%",
               "50%",
               "75%", "100%")
  ) +
  xlab("Replicated Edges") +
  ylab("") +
  facet_grid(n_new ~ facet, scales = "free_y") +
  scale_y_continuous(expand = c(0, 0)) 
```


# Figure 4: Forbes

```{r}
pcors_forbes  <- corpcor::cor2pcor( cor(BGGM::depression_anxiety_t1))

# forbes

net_forbes <- ifelse(abs(pcors_forbes[upper.tri(pcors_forbes)]) < 0.05, 0,  
                   pcors_forbes[upper.tri(pcors_forbes)] )


edges_forbes <- abs(net_forbes[net_forbes != 0])

p <- ncol(pcors_forbes)
n_t <- 0.5 * (p * (p-1))
n_e <- length(edges_forbes)


res_forbes <- lapply(1:length(n), function(x){
  
  pwr_un <- power_z(edges_forbes, n = n[x], c = p - 2, alpha = 0.05)
  pwr_cor <- power_z(edges_forbes, n = n[x], c = p - 2, alpha = 0.05 / n_t)
  
  
  
  dat_un <- data.frame(x = rep(0:n_e,2), 
                       Networks = rep(c('2_un', "4_un"), each = n_e + 1),
                       prob = c(poibin::dpoibin(0:n_e, 
                                                pp = pwr_un^2), 
                                poibin::dpoibin(0:n_e, 
                                                pp = pwr_un^4)),
                       sample = paste0("N = ", n[x]), alpha = "un")
  
  dat_cor <- data.frame(x = rep(0:n_e,2), 
                        Networks = rep(c('2_cor', "4_cor"), each = n_e + 1),
                        prob = c(poibin::dpoibin(0:n_e, 
                                                 pp = pwr_cor^2), 
                                 poibin::dpoibin(0:n_e, 
                                                 pp = pwr_cor^4)),
                        sample = paste0("N = ", n[x]), alpha = "cor")
  
  rbind.data.frame(dat_un, dat_cor)
  
})


dat_res <- do.call(rbind.data.frame, res_forbes)
dat_res$facet <- "Depression/Anxiety"


dat_res$n_new <- factor(dat_res$sample,
                        levels = rev(unique(dat_res$sample)),
                        labels = rev(unique(dat_res$sample)))

plt_forbes <- ggplot(data =  dat_res,
                     aes(
                       x = x ,
                       y  = prob,
                       group = Networks,
                       fill = Networks
                     )) +
  geom_area(position  = "identity",
            alpha = 0.75,
            color = "black") +
  theme_bw() +
  geom_vline(xintercept = 0.50 * n_e,
             linetype = "dotted",
             size = 0.5) +
  annotate(
    "rect",
    ymin = 0,
    ymax = Inf,
    xmin = 0.50 * n_e,
    xmax = Inf ,
    alpha = 0.05
  ) +
  geom_vline(xintercept = 0.50 * n_e,
             linetype = "dotted",
             size = 0.5) +
  
  theme(
    legend.position = "top",
    panel.spacing.y =  unit(1, "lines"),
    panel.grid = element_blank(),
    axis.title = element_text(size = 12),
    strip.background = element_rect(fill = "grey97"),
  )  +
  scale_fill_manual(values = c("#56B4E9",
                               "#0072B2",
                               "#E69F00",
                               "#D55E00")) +
  scale_x_continuous(
    limits = c(0, n_e),
    breaks = c(0,
               0.25 * n_e,
               0.50 * n_e,
               0.75 * n_e,
               1 * n_e),
    labels = c("0%",
               "25%",
               "50%",
               "75%", "100%")
  ) +
  xlab("") +
  ylab("") +
  facet_grid(n_new ~ facet, scales = "free_y") +
  scale_y_continuous(expand = c(0, 0))
```



# Figure 4: Combine

```{r}
cowplot::plot_grid(
  cowplot::get_legend(plt_bfi +
                        scale_fill_manual(
                          values = c("#56B4E9", "#0072B2", "#E69F00",  "#D55E00"),
                          labels = c(expression("2" ~
                                                "(" * alpha * " = 0.05 /" ~ italic(n)[t] * ")"),
                                     expression("2" ~
                                                  "(" * alpha * " = 0.05)"),
                                     expression("4" ~
                                                  "(" * alpha * " = 0.05 /" ~ italic(n)[t] * ")"),
                                     expression("4" ~
                                                  "(" * alpha * " = 0.05)")
                                     ))),
  cowplot::plot_grid(
    plt_bfi + theme(legend.position = "none"),
    plt_ptsd + theme(legend.position = "none"),
    plt_forbes + theme(legend.position = "none"),
    nrow = 1
  ),
  nrow = 2,
  rel_heights = c(1, 10)
)

```